# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/175v8nRxufNz4lyCL1jllYl5i10SRYbn8
"""

n= int(input('몇 팩토리얼?: '))
factorial= 1
for i in range(n,0,-1):
  factorial*= i
print(f'{n}!={factorial}')
  print()

"""n개의 정수의 합"""

import random


a = random.randrange(1, 101, 1)
num = -1

try =0

print("게임을 시작합니다")

while ( a != num ):

    num = int(input("1 ~ 100 사이의 숫자를 입력하세요 : "))

    if (num > a):
        print("down")
    elif (num < a):
        print("up")

    try += 1
print(try, "번 만에 정답을 맞추셨습니다.")

li_idol=['a','b','c','d','e']
li_idol.append('ffdf')
li_idol.insert(2,'dhdhdh')
li_idol[3]=['shshsh']
li_idol.remove('ffdf')
print(li_idol)

import random
li_num= []
for _ in range(100):
  li_num.append(random.randint(1,1000))
print("항목수: ", len(li_num))
print("합계: ", sum(li_num))
print("최대값: ", max(li_num))
print("최소값: ", min(li_num))
print("평균: ", sum(li_num)/len(li_num))

print

a= input("사용자 입력: ")
sale=0
discount_percent=0
discount_cost=0
pay=0
if a >= 100000:
  dc=10
elif a >= 50000:
  dc=7.5
elif a >= 10000:
  dc=5
else:
  dc=0
print(f'할인률: {dc}%')

age=input('나이를 입력해주세요')
if age>= 65 or age<=7:
  print('입장료는 무료입니다')
else:
  age>=8 and age<=18
  print('1000원입니다')

n= int(input('몇개의 숫자를 더할까요? :'))
sum= 0
for i in range(n):
  num= int(input('정수입력: '))